refactor
Deefoozy/MultiThreadedWebSocketServer pull request #19
Opened 2019-10-06 18:28 UTC by IRusio

i swapped few for loops on foreach, added one DRY function, switched variables on var

2019-10-06 21:28 UTC, Deefoozy requested changes
Thanks for the PR!
I'm going to have to go through this code again to make sure i have not missed anything.
Some comments may appear illogical or not the same as the C# conventions (think var naming), however i would like to keep that consistent and avoid issues (like having to rename a well named variable due to the type having the same name and capitalization)
I would also like to minimise the use of vars except there are complex datatypes or the new keyword is used (`List<Dictionary<string, SomeObject>> dictionary List = new List<Dictionary<string, SomeObject>>();` or `Type thing = new Type`)

**EDIT :** No more vars!

2019-10-06 21:28 UTC, Deefoozy commented on WebSocketTest/Programs/TcpServer.cs
> +		private static bool _isAccepting = true; //Im' not sure that should work in this way?
It works as intended, it is a way to be able to close the server when all threads have closed.

2019-10-06 21:28 UTC, Deefoozy commented on WebSocketTest/Responses/Handshake.cs
> +			var secWebSocketKeyPosition = clientRequest.IndexOf(CLIENT_KEY_REQUEST_HEADER, StringComparison.Ordinal) + CLIENT_KEY_REQUEST_HEADER.Length;
Don't use vars for primitive types

2019-10-06 21:28 UTC, Deefoozy commented on WebSocketTest/Responses/Handshake.cs
> +			var receivedKey = clientRequest.Substring(secWebSocketKeyPosition, 24);
Don't use vars for primitive types

2019-10-06 21:28 UTC, Deefoozy commented on WebSocketTest/Responses/Handshake.cs
> +			var responseKey = receivedKey + SERVER_KEY;
Don't use vars for primitive types

2019-10-06 21:28 UTC, Deefoozy commented on WebSocketTest/Responses/Handshake.cs
> +			var responseKeyHash = Convert.ToBase64String(
Don't use vars for primitive types

2019-10-06 21:28 UTC, Deefoozy commented on WebSocketTest/Models/Clients/Client.cs
> +		public readonly int Id;
I want to use camelCase for member variables to avoid naming conflicts with classes

2019-10-06 21:28 UTC, Deefoozy commented on WebSocketTest/Models/Clients/Client.cs
> +		public readonly TcpClient ClientTcp;
I want to use camelCase for member variables to avoid naming conflicts with classes (tcpClient or client should be fine)

2019-10-06 21:28 UTC, Deefoozy commented on WebSocketTest/Models/GameObjects/GameObject.cs
> +    internal class GameObject : IPhysicsData
Use of spaces instead of tabs

2019-10-06 21:28 UTC, Deefoozy commented on WebSocketTest/Decoders/JsonDecoder.cs
> +    internal static class JsonDecoder
Use of spaces instead of tabs

2019-10-06 21:28 UTC, Deefoozy commented on WebSocketTest/Models/GameObjects/GameObject.cs
> +        {
Use of spaces instead of tabs

2019-10-06 21:28 UTC, Deefoozy commented on WebSocketTest/Models/GameObjects/GameObject.cs
> +            Init(
Use of spaces instead of tabs

2019-10-06 21:28 UTC, Deefoozy commented on WebSocketTest/Models/GameObjects/GameObject.cs
> +        }
Use of spaces instead of tabs

2019-10-06 21:28 UTC, Deefoozy commented on WebSocketTest/Models/GameObjects/GameObject.cs
> +        {
Use of spaces instead of tabs

2019-10-06 21:28 UTC, Deefoozy commented on WebSocketTest/Models/GameObjects/GameObject.cs
> +            Init(
Use of spaces instead of tabs

2019-10-06 21:28 UTC, Deefoozy commented on WebSocketTest/Models/GameObjects/GameObject.cs
> +        }
Use of spaces instead of tabs

2019-10-06 21:28 UTC, Deefoozy commented on WebSocketTest/Models/GameObjects/Player.cs
> +    internal class Player : GameObject
Use of spaces instead of tabs

2019-10-06 21:28 UTC, Deefoozy commented on WebSocketTest/Models/Games/Game.cs
> +		public bool IsReady;
camelCase + revert to ready

2019-10-06 21:28 UTC, Deefoozy commented on WebSocketTest/Models/Games/Game.cs
> +		public int PlayerAmount;
camelCase

2019-10-06 21:28 UTC, Deefoozy commented on WebSocketTest/Models/Games/Game.cs
> +				var framecounter = 0;
Use of var for primitive types

2019-10-06 21:28 UTC, Deefoozy commented on WebSocketTest/Models/Vectors/Dimensions2d.cs
> +    internal class Dimensions2d : Vector2d
Use of spaces instead of tabs

2019-10-06 21:28 UTC, Deefoozy commented on WebSocketTest/Models/Vectors/Position2d.cs
> +    internal class Position2d : Vector2d
use of spaces instead of tabs

2019-10-06 21:28 UTC, Deefoozy commented on WebSocketTest/Models/Vectors/Vector2d.cs
> +    internal class Vector2d : IVector2d
Use of spaces instead of tabs

2019-10-06 21:28 UTC, Deefoozy commented on WebSocketTest/Models/Vectors/Velocity2d.cs
> +        public Velocity2d(int x, int y) : base(x, y) { }
Use of spaces instead of tabs

2019-10-06 21:28 UTC, Deefoozy commented on WebSocketTest/Models/Vectors/Velocity2d.cs
> +    internal class Velocity2d : Vector2d
Use of spaces instead of tabs

2019-10-06 21:28 UTC, Deefoozy commented on WebSocketTest/Programs/TcpServer.cs
> +    internal static class TcpServer
Use of spaces instead of tabs

2019-10-06 21:28 UTC, Deefoozy commented on WebSocketTest/Programs/TcpServer.cs
> +		private static readonly IPEndPoint Endpoint = new IPEndPoint(IPAddress.Any, 8079); // TODO: auto free port finder
Write an issue instead of writing a comment in code so it is documented as a possible improvement. (revert port change / comment)

2019-10-06 21:28 UTC, Deefoozy commented on WebSocketTest/Programs/TcpServer.cs
> +		public static int ConnectionAmount;
camelCase

2019-10-06 21:28 UTC, Deefoozy commented on WebSocketTest/Programs/TcpServer.cs
> +				var client = server.AcceptTcpClient();
avoid usage of var for simple types

2019-10-06 21:28 UTC, Deefoozy commented on WebSocketTest/ResponseHandlers/MessageSender.cs
> +            foreach (var targetClient in targetClients)
Use of spaces instead of tabs (whole foreach block)

2019-10-06 21:28 UTC, Deefoozy commented on WebSocketTest/ResponseHandlers/MessageSender.cs
> +        }
Use of spaces instead of tabs

2019-10-06 21:28 UTC, Deefoozy commented on WebSocketTest/ResponseHandlers/MessageSender.cs
> +        /// <summary>
Use of spaces instead of tabs (until line 57)

2019-10-06 21:28 UTC, Deefoozy commented on WebSocketTest/ResponseHandlers/MessageSender.cs
> +        {
Use of spaces instead of tabs (until line 71)

2019-10-06 21:28 UTC, Deefoozy commented on WebSocketTest/ResponseHandlers/MessageSender.cs
> +        private static void PrintErrorInSending(Client targetClient)
Use of spaces instead of tabs (until line 88)

2019-10-06 21:28 UTC, Deefoozy commented on WebSocketTest/Responses/Handshake.cs
> +    internal static class Handshake
Use of spaces instead of tabs

2019-10-06 21:28 UTC, Deefoozy commented on WebSocketTest/Responses/Message.cs
> +                // opCode = content type
Use of spaces instead of tabs

2019-10-06 21:28 UTC, Deefoozy commented on WebSocketTest/Responses/Message.cs
> +                byte[] buffer;
Use of spaces instead of tabs

2019-10-07 19:44 UTC, LDSpits approved these changes
LGTM, When you address the comments of @Deefoozy it'll be merged. Thanks for the PR!

2019-10-09 13:00 UTC, IRusio commented
tabs vs spaces war 😆 your repo, your rules. I will change that, in weekend.
in my opinion var is better option, when we change sth, its more generic etc. when we change sth on another form of communication etc

2019-10-09 16:00 UTC, Deefoozy commented
Sorry about that! didn't know i could've generated a .editorconfig, but it is now in develop.
@LDSpits and I chose for the explicit only approach (No vars at all anymore!) to keep everything "simple", Yes if you have complex types it hurts to type it all out, Yes a good editor is smart enough to tell you the type, No vars are not alower, But, we are the stubborn old people kind of coder, sorry about that!

2019-11-02 15:25 UTC, closed without merging